### ISSUE TITLE
Switch to a github org?

### ISSUE THREAD

**Issue by nbashaw** [kyro/shelfies#5]
@kyro want me to transfer this to your acct, or make a new github org? Doesn't really fit under my name (since this is really your creation)

**Comment by kyro** [comment]
@nbashaw Sure, you can transfer it. Anything I need to do on my end?

**Comment by nbashaw** [comment]
@kyro I just put in the transfer request - all you have to do is accept it

**Comment by kyro** [comment]
@nbashaw thanks a lot, and for the help getting this up and running.

**Comment by nbashaw** [comment]
@kyro definitely! i'll keep contributing, just want to make sure you have proper ownership

**Comment by kyro** [comment]
awesome, i appreciate it!
